@startuml
class ReprodutorMusical implements DispositivoMultifuncional {
    + void tocar()
    + void pausar()
    + void selecionarMusica(String musica)
}

class AparelhoTelefonico implements DispositivoMultifuncional {
    + void ligar(String numero)
    + void atender()
    + void iniciarCorreioVoz()
}

class NavegadorNaInternet implements DispositivoMultifuncional {
    + void exibirPagina(String url)
    + void adicionarNovaAba()
    + void atualizarPagina()
}

interface DispositivoMultifuncional{
    + void tocar()
    + void pausar()
    + void selecionarMusica(String musica)
    + void ligar(String numero)
    + void atender()
    + void iniciarCorreioVoz()
    + void exibirPagina(String url)
    + void adicionarNovaAba()
    + void atualizarPagina()
}

@enduml
